Ndarrays, Indexing, and Slicing

In [2]:
#Start by importing the numpy and pandas library

import numpy as np
import pandas as pd

#Try creating a 4 row x 4 column array of integers


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [3]:
#let's try altering this array. First, let's save a sopy of this array
int_ar2 = int_ar1.copy()

In [4]:
#Next, let's change the entire first row to twos (2)


array([[2, 2, 2, 2],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [5]:
#With some for loops, we can more dynamically change our arrays. 
# Change the diagonal to a new number.



array([[10,  2,  2,  2],
       [ 1, 10,  1,  1],
       [ 1,  1, 10,  1],
       [ 1,  1,  1, 10]], dtype=int32)

In [6]:
#We can also change the contents of an array through arithmetic procedures.
# Multiply the values by some number.


array([[20,  4,  4,  4],
       [ 2, 20,  2,  2],
       [ 2,  2, 20,  2],
       [ 2,  2,  2, 20]], dtype=int32)

In [7]:
# Subtract some number

array([[ 5, -3, -3, -3],
       [-4,  5, -4, -4],
       [-4, -4,  5, -4],
       [-4, -4, -4,  5]], dtype=int32)

Arrays and Matrices

In [8]:
#Confirm that the array is 4x4
#Remembers, arrays are given by ----> # of rows X # of columns.


(4, 4)

In [9]:
#Okay, now try and create a 5 x 5 array of ones



array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
#Create 3 identity matrices of any size

array([[1., 0.],
       [0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Quick List Comprehension/Lambda function Exercises

In [11]:
# 1
# make a list comprehension which filters the even numbers 
#out of the following numpy array: np.arange(1,100,3)

In [13]:
# 2 for the following mispelled list of Beatles, write a function correct_beatles,
# then use the built-in map function to create a corrected list of Beatles.

beatle_list = ['John', 'Rango', 'Pal', 'Geoge', 
               'Rungo', 'Gage', 'Pul', 'Jonathan', 'Mike']

def correct_beatles(name):
    
    pass
        
correct_list = map()
print(list(correct_list)